### PR TITLE
fix: preserve tag filter after toggling assignment status

### LINKED ISSUE #89: Tag filter is lost after activating an assignment
## Environment

- Operating System: Windows 11
- Java: 17 (Temurin 17.0.18)
- Spring profile: `mysql`

---

## Preconditions

- At least two assignments exist.
- The assignments have different tags (e.g., `sample` and `kotlin`).
- The assignments are inactive.

---

## Steps to Reproduce

1. Log in as a teacher (e.g., `teacher1 / 123`).
2. Navigate to **Assignments → Current Assignments**.
3. In the **Tags** filter, select a specific tag (e.g., `kotlin`).
4. Confirm that the list is correctly filtered (only assignments with that tag are displayed).
5. Click the checkbox in the **"Active?"** column to activate the assignment (if it is already active, deactivate it).

---

## Expected Result

The assignment should be activated and the selected tag filter should remain applied.

---

## Actual Result

The assignment is successfully activated, but the tag filter is lost.  
The page returns to the default state and all assignments are displayed again.

---

## Screenshots

Below are screenshots that help visualize and reproduce the issue.

Image

Image

Image

Image

Image

Image

Image

### PR DESCRIPTION
**Pull request by Gasg10**
Fixes #89

## Problem
When a tag filter was applied in the Current Assignments page and the teacher toggled the Active? checkbox, the tag filter was lost after the redirect. The page returned to the default state showing all assignments.

## Root Cause
The `toggleAssignmentStatus` controller did not receive or preserve the active tag filter. After toggling, it always redirected to `/assignment/my` without any query parameters, discarding the selected tags.

## Fix
Three changes were made:

**1. `AssignmentController.kt`** — Added `tags` as a `@RequestParam` to `toggleAssignmentStatus` and used a local variable for the redirect:
```kotlin
fun toggleAssignmentStatus(@PathVariable assignmentId: String,
                           @RequestParam(name = "tags", required = false) tags: String?,
                           ...): String {
    val redirectUrl = if (tags != null) "redirect:/assignment/my?tags=$tags" else "redirect:/assignment/my"
    ...
    return redirectUrl
}
```

**2. `AssignmentController.kt`** — Added `currentTags` to the model in `listMyFilteredAssignments`:
```kotlin
model["currentTags"] = tags ?: ""
```

**3. `teacher-assignments-list.html`** — Added a hidden input to pass the current tags when the toggle form is submitted:
```html
<form th:action="@{'/assignment/toggle-status/' + ${assignment.id}}" method="post">
    <input type="hidden" name="tags" th:value="${currentTags}"/>
    ...
</form>
```

## Testing
1. Start the application locally
2. Log in as teacher
3. Navigate to Assignments → Current Assignments
4. Select a tag filter (e.g. `kotlin`) — only filtered assignments are shown
5. Toggle the Active? checkbox of an assignment
6. The tag filter is now preserved after the redirect

### CODE REVIEW

File: src/test/kotlin/org/dropProject/controllers/AssignmentControllerTests.kt [hunk 1]
```diff
@@ -2086,44 +2086,28 @@ class AssignmentControllerTests {
...
-                .param("acl", "teacher2 teacher3")  // space instead of comma
-        )
-            .andExpect(status().isOk())
-            .andExpect(view().name("assignment-form"))
-            .andExpect(model().attributeHasFieldErrors("assignmentForm", "acl"))
-    }
 
-    @Test
+
+@Test
```
Comment (palves-ulht) [inline src/test/kotlin/org/dropProject/controllers/AssignmentControllerTests.kt]: This line is not properly indented

**Review by palves-ulht — CHANGES_REQUESTED** [review]
Please resolve the conflicts first

**Comment by Gasg10** [comment]
Fix!

**Review by palves-ulht — APPROVED** [review]
